#!/bin/bash
local_variables=$(set -o posix; set | grep -E '^[a-zA-Z_][a-zA-Z_0-9]*=')
environment_variables=$(env)
functions=$(declare -F | awk '{print $3}')
echo "Local Variables:"
echo "$local_variables"
echo "Environment Variables:"
echo "$environment_variables"
echo "Functions:"
echo "$functions"
